modLoader="javafml"
loaderVersion="[4,)"
license="MIT (code) / All Rights Reserved (assets)"

[[mods]]
modId="frogportnetworks"
version="1.0.0"
displayName="Frogport Networks"
description='''A Create addon that adds IP networking to Minecraft.'''

[[dependencies.frogportnetworks]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.frogportnetworks]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.frogportnetworks]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.frogportnetworks]]
modId="jei"
type="optional"
versionRange="[19.0.0,)"
ordering="AFTER"
side="CLIENT"